import { Inter } from "next/font/google";
import { Container,Stack,Typography } from "@mui/material";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inventory Management App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Container>
        <Stack sx={{justifyContent:"center",alignItems:'center'}} paddingX={5} paddingY={3} direction={'row'}>
          <Typography variant='h4' sx={{width:300,textAlign:'center'}}>Thadiel&apos;s Pantry Management App</Typography>
        </Stack>
        {children}
      </Container>
      </body>
    </html>
  );
}
